# Generated by Django 3.2.5 on 2021-08-19 20:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20210818_0048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopuser',
            options={'ordering': ('-is_active', '-is_superuser', '-is_staff', 'username')},
        ),
        migrations.AddField(
            model_name='shopuser',
            name='activation_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='activation_key_expired',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 21, 20, 53, 26, 326975, tzinfo=utc)),
        ),
    ]
