# Generated by Django 3.2.6 on 2021-08-30 16:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20210820_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expired',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 1, 16, 24, 26, 340956, tzinfo=utc)),
        ),
    ]
