<<<<<<< HEAD
# Generated by Django 3.2.6 on 2021-08-30 16:24
=======
# Generated by Django 3.2.6 on 2021-08-20 12:59
>>>>>>> 371dca890ac97364ef991ad93f1874cca72754b1

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20210820_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expired',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 1, 16, 24, 26, 340956, tzinfo=utc)),
=======
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 22, 12, 59, 11, 70945, tzinfo=utc)),
>>>>>>> 371dca890ac97364ef991ad93f1874cca72754b1
        ),
    ]
